MadPay724.Shop.Test/Models/ErrorViewModel.cs
using System;

namespace MadPay724.Shop.Test.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MadPay724.Shop.Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MadPay724.Shop.Test.Models;
using MadPay724.AspNetCore.GateWay;

namespace MadPay724.Shop.Test.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MadPay724.Shop.Test/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MadPay724.AspNetCore.GateWay;
using MadPay724.AspNetCore.GateWay.Models;
using Microsoft.AspNetCore.Mvc;

namespace MadPay724.Shop.Test.Controllers
{
    public class PayController : Controller
    {
        private readonly IMadPayGateWay _madPayGateWay;

        public PayController(IMadPayGateWay madPayGateWay)
        {
            _madPayGateWay = madPayGateWay;
        }
        public async Task<IActionResult> Index(int price)
        {
            var request = new MadPayGatePayRequest
            {
                Api = "5eac1a0d-47c9-433b-9b5c-847c2ba979bd",
                RedirectUrl = "https://localhost:44333/verify/index",
                FactorNumber = "968574",
                Amount = price,

                UserName = "کیوان",
                Email = "key.one72@gmail.com",
                Mobile = "09361234569",
                Description = "خرید از سایت کفش چرم",
                ValidCardNumber = ""
            };

            var result = await _madPayGateWay.PayAsync(request);
            if (result.Status)
            {
                return Redirect(result.Result.RedirectUrl);
            }
            else
            {
                return View(result);
            }
        }
    }
}

MadPay724.Shop.Test/Controllers/VerifyController.cs
using MadPay724.AspNetCore.GateWay;
using MadPay724.AspNetCore.GateWay.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MadPay724.Shop.Test.Controllers
{
    public class VerifyController : Controller
    {
        private readonly IMadPayGateWay _madPayGateWay;

        public VerifyController(IMadPayGateWay madPayGateWay)
        {
            _madPayGateWay = madPayGateWay;
        }
        public async Task<IActionResult> Index(string token)
        {
            var model = new MadPayGateVerifyRequest
            {
                Api = "5eac1a0d-47c9-433b-9b5c-847c2ba979bd",
                Token = token
            };

            var result = await _madPayGateWay.VerifyAsync(model);

            return View(result);
        }
    }
}

MadPay724.Shop.Test/Views/Home/Index.cshtml
    @{
        ViewData["Title"] = "فروشگاه کفش چرم";
    }

    <div class="text-center">
        <h1 class="display-4">نهایی کردن پرداخت</h1>
        <br />
        <div class="alert alert-warning" role="alert">
            لطفا هرگونه نرم افزار vpn خودرا خاموش کنید در پروسه پرداخت
        </div>
        <br />
        <h2>کفش مردانه ی چرم اصل ایرانی <span class="badge badge-secondary">300,000 تومان</span></h2>
        <br />
        <br />
        <br />
        @using (Html.BeginForm("Index", "Pay"))
        {
            <div class="form-group">
                <label for="exampleInputEmail1">قیمت قابل پرداخت</label>
                <input type="text" name="price" value="300000" class="form-control" aria-describedby="emailHelp" placeholder="قیمت مورد نظر را وارد کنید">
                <small id="emailHelp" class="form-text text-muted">مبلغ به تومان میباشد ...</small>
            </div>

            <button type="submit" class="btn btn-success">پرداخت نهایی با درگاه بانک ملت</button>

        }

    </div>

MadPay724.Shop.Test/Views/Pay/Index.cshtml
@using MadPay724.AspNetCore.GateWay.Models
@model MadPayGateResult<MadPayGatePayResponse>

@{
    ViewData["Title"] = "فروشگاه کفش چرم";
}
    <div class="text-center">
        <button type="button" class="btn btn-danger">پرداخت شما موفقیت نبود</button>
        <br />
        <div class="alert alert-danger" role="alert">
            @foreach (var error in Model.Messages)
            {
                <span>@error</span>
            }
        </div>
        <br />
        <h2>کفش مردانه ی چرم اصل ایرانی <span class="badge badge-secondary">300,000 تومان</span></h2>
    </div>

MadPay724.Shop.Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MadPay724.Shop.Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MadPay724.Shop.Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MadPay724.Shop.Test/Views/Verify/Index.cshtml
@using MadPay724.AspNetCore.GateWay.Models
@model MadPayGateResult<MadPayGateVerifyResponse>
@{
    ViewData["Title"] = "فروشگاه کفش چرم";
}

    <div class="text-center">
        @if (Model.Status)
        {
            <button type="button" class="btn btn-success">پرداخت شما با موفقیت انجام شد</button>
            <br />
            <div class="alert alert-info" role="alert">
                @foreach (var error in Model.Messages)
                {
                    <span>@error</span>
                }
            </div>
            <br />
            <h2>کفش مردانه ی چرم اصل ایرانی <span class="badge badge-secondary">300,000 تومان</span></h2>

        }
        else
        {
            <button type="button" class="btn btn-danger">پرداخت شما موفقیت نبود</button>
            <br />
            <div class="alert alert-danger" role="alert">
                @foreach (var error in Model.Messages)
                {
                    <span>@error</span>
                }
            </div>
            <br />
            <h2>کفش مردانه ی چرم اصل ایرانی <span class="badge badge-secondary">300,000 تومان</span></h2>

        }

    </div>